# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 15:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_no', models.CharField(max_length=30)),
                ('model_name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Parking_lot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_name', models.CharField(max_length=300)),
                ('lot_id', models.CharField(max_length=30)),
                ('lot_address', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plot_id', models.CharField(max_length=30)),
                ('plate_no', models.CharField(max_length=30)),
                ('check_in_time', models.TimeField()),
                ('check_out_time', models.TimeField()),
                ('amount', models.IntegerField()),
                ('flag', models.CharField(max_length=2)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='User_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField()),
                ('legal_id', models.CharField(max_length=300)),
                ('resource', models.CharField(max_length=300)),
                ('contact', models.CharField(max_length=20)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
